"""Facade: everything that lived in bot/handlers.py, re-exported from domain modules.

Public API (router, handlers, state objects, module refs) must stay identical so
that bot/main.py, web/hook.py and the test-suite keep working unchanged.
"""

from aiogram.filters import Command

from ._common import (
    AMOUNT_RE,
    BET_ID_RE,
    BET_LINK_RE,
    DEADLINE_RE,
    DONATE_LINK_RE,
    HELP,
    KIND_EMOJI,
    PAYWALL_LINK_RE,
    QUICK_AMOUNTS,
    SIG_RE,
    TX_HASH_RE,
    USDC_ADDR_RE,
    _bot_username,
    _edit_menu,
    _esc,
    _fmt,
    _get_bot_username,
    _menu_kb,
    _money_cmd_last,
    _now,
    _qr_bytes,
    _throttle,
    _to_micro,
    base,
    config,
    ledger,
    qrlib,
    router,
    wallets,
)
from .agent import cmd_agent
from .ai import (
    AI_BOT_COMMAND,
    cmd_ask,
)
from .basename import cb_basename, cmd_basename
from .breakthrough import (
    cmd_gasless,
    cmd_subscribe,
    cmd_subscriptions,
    cmd_cancel_sub,
    cmd_credit,
    cmd_create_token,
    cmd_buy_token,
    cmd_claim_dividends,
)
from .bets import (
    _bet_card,
    _bet_create,
    _bet_place,
    _bets_text,
    _market_detail_text,
    _notify_bet_cancelled,
    _notify_bet_result,
    _parse_deadline,
    _rel_deadline,
    cb_bet_amount,
    cb_bet_place,
    cb_market,
    cb_res,
    cmd_bet,
    cmd_bets,
    cmd_cancel,
    cmd_mybets,
    cmd_resolve,
)
from .markets import (
    _market_card,
    _market_create,
    _markets_text,
    _notify_market_result,
    cb_market_card,
    cb_market_list,
    cb_mk_buy,
    cb_mk_cancel,
    cb_mk_do,
    cb_mk_resolve,
    cb_mk_sell,
    cb_mk_selldo,
    cmd_market,
    cmd_markets,
    cmd_positions,
    cmd_sell,
    cmd_trade,
)
from .menu import (
    _donate_landing,
    _send_market_deep_link,
    _send_paywall_deep_link,
    _settings_kb_text,
    cb_menu,
    cb_paywall_buy,
    cb_settings,
    cmd_broadcast,
    cmd_menu,
    cmd_settings,
    cmd_start,
    on_menu,
)
from .onchain import (
    cb_oc_resolve,
    cmd_oc,
    cmd_oc_buy,
    cmd_oc_create,
    cmd_oc_pos,
    cmd_oc_redeem,
    cmd_oc_resolve,
    cmd_oc_sell,
)
from .paywall import (
    PAYWALL_DRAFT_TTL,
    PAYWALL_HELP,
    _index_message,
    _paywall_channel_cmd,
    _paywall_channels_cmd,
    _paywall_draft,
    _paywall_subscribe_cmd,
    cmd_paywall,
    on_reaction,
)
from .stats import (
    _history_text,
    _stats_text,
    _top_text,
    cmd_history,
    cmd_stats,
    cmd_top,
)
from .tips import _notify_tip_received, _resolve_in_chat, cmd_rain, cmd_tip
from .wallet import (
    _balance_text,
    _deposit_text,
    _donate_text,
    _ensure_wallet,
    cb_wallet_new,
    cb_wallet_sel,
    cmd_balance,
    cmd_claim,
    cmd_confirm,
    cmd_deposit,
    cmd_donate,
    cmd_export,
    cmd_import,
    cmd_link,
    cmd_tx,
    cmd_wallet,
    cmd_withdraw,
)

# Register breakthrough feature handlers
router.message.register(cmd_gasless, Command('gasless'))
router.message.register(cmd_subscribe, Command('subscribe'))
router.message.register(cmd_subscriptions, Command('subscriptions'))
router.message.register(cmd_cancel_sub, Command('cancelsub'))
router.message.register(cmd_credit, Command('credit'))
router.message.register(cmd_create_token, Command('createtoken'))
router.message.register(cmd_buy_token, Command('buytoken'))
router.message.register(cmd_claim_dividends, Command('claim'))

# IMPORTANT: the filter-less catch-all `_index_message` must be registered AFTER
# every command handler — aiogram stops on the first matching handler, so a
# catch-all registered earlier would swallow /tip, /rain and any other command.
# Import order alone is too fragile (formatters re-sort imports), so the
# registration is done explicitly here, at the very end of the package init.
_index_message = router.message()(_index_message)

__all__ = [
    "AI_BOT_COMMAND",
    "AMOUNT_RE",
    "BET_ID_RE",
    "BET_LINK_RE",
    "DEADLINE_RE",
    "DONATE_LINK_RE",
    "HELP",
    "KIND_EMOJI",
    "PAYWALL_DRAFT_TTL",
    "PAYWALL_HELP",
    "PAYWALL_LINK_RE",
    "QUICK_AMOUNTS",
    "SIG_RE",
    "TX_HASH_RE",
    "USDC_ADDR_RE",
    "_balance_text",
    "_bet_card",
    "_bet_create",
    "_bet_place",
    "_bets_text",
    "_bot_username",
    "_deposit_text",
    "_donate_landing",
    "_donate_text",
    "_edit_menu",
    "_ensure_wallet",
    "_esc",
    "_fmt",
    "_get_bot_username",
    "_history_text",
    "_index_message",
    "_market_card",
    "_market_create",
    "_market_detail_text",
    "_markets_text",
    "_menu_kb",
    "_money_cmd_last",
    "_notify_bet_cancelled",
    "_notify_bet_result",
    "_notify_market_result",
    "_notify_tip_received",
    "_now",
    "_parse_deadline",
    "_paywall_channel_cmd",
    "_paywall_channels_cmd",
    "_paywall_draft",
    "_paywall_subscribe_cmd",
    "_qr_bytes",
    "_rel_deadline",
    "_resolve_in_chat",
    "_send_market_deep_link",
    "_send_paywall_deep_link",
    "_settings_kb_text",
    "_stats_text",
    "_throttle",
    "_to_micro",
    "_top_text",
    "base",
    "cb_basename",
    "cb_bet_amount",
    "cb_bet_place",
    "cb_market",
    "cb_market_card",
    "cb_market_list",
    "cb_menu",
    "cb_mk_buy",
    "cb_mk_cancel",
    "cb_mk_do",
    "cb_mk_resolve",
    "cb_mk_sell",
    "cb_mk_selldo",
    "cb_oc_resolve",
    "cb_paywall_buy",
    "cb_res",
    "cb_settings",
    "cb_wallet_new",
    "cb_wallet_sel",
    "cmd_agent",
    "cmd_ask",
    "cmd_balance",
    "cmd_basename",
    "cmd_bet",
    "cmd_bets",
    "cmd_broadcast",
    "cmd_cancel",
    "cmd_claim",
    "cmd_confirm",
    "cmd_deposit",
    "cmd_donate",
    "cmd_export",
    "cmd_history",
    "cmd_import",
    "cmd_link",
    "cmd_market",
    "cmd_markets",
    "cmd_menu",
    "cmd_mybets",
    "cmd_oc",
    "cmd_oc_buy",
    "cmd_oc_create",
    "cmd_oc_pos",
    "cmd_oc_redeem",
    "cmd_oc_resolve",
    "cmd_oc_sell",
    "cmd_paywall",
    "cmd_positions",
    "cmd_rain",
    "cmd_resolve",
    "cmd_sell",
    "cmd_settings",
    "cmd_start",
    "cmd_stats",
    "cmd_tip",
    "cmd_top",
    "cmd_trade",
    "cmd_tx",
    "cmd_wallet",
    "cmd_withdraw",
    "config",
    "ledger",
    "on_menu",
    "on_reaction",
    "qrlib",
    "router",
    "wallets",
]
