"""AI-agent demo — the "wow" clip for reviewers: an autonomous agent mints a
paywalled post from a headline and then pays its own way in via x402.

For the Loom video. The agent part that needs real money (leg 2) is printed,
not executed; everything else runs against the live bot/ledger.

Usage:
    python scripts/agent_demo.py "ETH breaks $5,000 on Base volume" --base https://your-host --price 1
"""

import argparse
import sys
from decimal import Decimal

from bot import config
from bot.ledger import ledger


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("headline")
    ap.add_argument("--base", required=True, help="public https URL of your deployed web server")
    ap.add_argument("--price", default="1", help="USDC price of the post")
    args = ap.parse_args()

    config.validate()
    title = args.headline[: config.PAYWALL_MAX_TITLE_LEN]
    price_micro = int(Decimal(args.price) * 10**config.USDC_DECIMALS)
    content = (
        f"Alpha snapshot generated by an autonomous agent at {__import__('time').ctime()}.\n"
        f"Headline: {args.headline}\n"
        "This post was minted and re-bought by the agent itself to demo "
        "the AI-agent-to-agent economy on Base."
    )

    item_id = ledger.create_paywall(0, title, price_micro, content)
    if item_id is None:
        print("ERROR: per-user paywall cap reached")
        sys.exit(1)
    print(f"[1] Agent minted paywall post #{item_id}: «{title}» for {args.price} USDC")

    path = f"/api/x402/paywall?item={item_id}&amount={args.price}"
    print(f"[2] Agent requests the invoice:  POST {args.base}{path}")
    print("[3] Agent signs the USDC transfer with its own key and repeats the request with x-402-payment: <tx>")
    print(f"[4] Agent reads the content from the 200 response; the owner is credited {args.price} USDC on-chain.")
    print(f"\nDemo clip commands:\n  python scripts/x402_demo.py paywall {item_id} --base {args.base}")


if __name__ == "__main__":
    main()
