"""Signal selling — agent creates a paywall post with its analysis.

The agent:
  1. Writes analysis as paywall content
  2. Creates paywall item via ledger
  3. Optionally buys it back via x402 (for demo)
  4. Returns the item_id so external agents can purchase it

This is the "Sell its analysis as paywalled signals via x402" job
from the SURGE-AGENT-PROMPT.
"""

import time

from bot import config
from bot.ledger import ledger

from . import caps


async def sell_signal(
    market_id: int,
    analysis: str,
    price_usdc: float = 1.0,
    title: str | None = None,
) -> dict:
    """Create a paywall post with the agent's market analysis.

    Returns: {"item_id": int, "price_usdc": float, "title": str}
    """
    err = caps.check_action(0.0)  # creating is free, buying costs money
    if err:
        return {"error": err}

    if not title:
        title = f"Signal: Market #{market_id} analysis ({time.strftime('%Y-%m-%d %H:%M')})"

    title = title[: config.PAYWALL_MAX_TITLE_LEN]
    price_micro = round(price_usdc * 10**config.USDC_DECIMALS)
    tg_id = 0  # agent's tg_id (0 = system)

    content = (
        f"🤖 Tippy Agent Signal\n"
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}\n"
        f"Market ID: {market_id}\n"
        f"---\n"
        f"{analysis}\n"
        f"---\n"
        f"This signal was generated by an autonomous AI agent on Base.\n"
        f"Pay {price_usdc} USDC via x402 to read the full analysis."
    )

    try:
        item_id = ledger.create_paywall(tg_id, title, price_micro, content)
        if item_id is None:
            caps.record_error()
            return {"error": "paywall cap reached"}
        caps.record_action(0.0)
        return {
            "item_id": item_id,
            "price_usdc": price_usdc,
            "title": title,
        }
    except Exception as e:
        caps.record_error()
        return {"error": str(e)}


async def buy_own_signal(item_id: int, base_url: str) -> dict:
    """Agent buys its own signal via x402 (for demo purposes).

    Returns: {"status": str, "content_preview": str}
    """
    import requests

    path = f"/api/x402/paywall?item={item_id}&amount=1"
    url = f"{base_url.rstrip('/')}{path}"

    try:
        # Leg 1: get invoice
        r1 = requests.post(url, timeout=30)
        if r1.status_code != 402:
            return {"error": f"Expected 402, got {r1.status_code}"}

        # For demo: we print the payment command instead of executing it
        invoice = r1.headers
        pay_to = invoice.get("x-402-recipient", "")
        amount = invoice.get("x-402-amount", "0")

        return {
            "status": "invoice_received",
            "pay_to": pay_to,
            "amount_micro": amount,
            "instruction": (
                f"To complete payment, send {int(amount) / 1_000_000} USDC to {pay_to} "
                f"on Base, then repeat the request with x-402-payment header."
            ),
        }
    except Exception as e:
        return {"error": str(e)}
